### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by millette** [ovhemert/gatsby-plugin-zopfli#3]
I was searching for a gatsby plugin to ship gzipped files. I found this and a brotli one, but then noticed a ```.gz``` extension in your readme so I took another look.

Turns out, zopli outputs (amongst other things) gzip format. I did not realize that before. Perhaps I'm not alone.

With all that in mind, seeing how zopfli is technically correct, it's mostly an implementation detail. Could this package be renamed to gatsby-plugin-gzip or clarify in the readme that for most cases, zopfli is just like gzip.

Thanks!

**Comment by ovhemert** [comment]
I've named the package "zopfli" on purpose, because there is a difference with the original gzip format. It makes the files actually a bit smaller. Naming the package "gzip" would be confusing I think, because people will associate it with the well-known compression format that almost every webserver supports out of the box.

I've just updated the intro of the package to clarify. Please read through it, and if you have any additions, you're welcome to comment / send in a PR.

Thanks for the feedback

**Comment by millette** [comment]
Thanks! The intro is clearer now. I undertand that zopfli is a backward compatible improvement over gzip. In fact, I would be suprised to see a ```gatsby-plugin-gzip``` appear. I will close the issue.
