### ISSUE TITLE
Run locally?

### ISSUE THREAD

**Issue by tbrannam** [ovhemert/gatsby-plugin-zopfli#4]
the readme suggests that `gatsby serve` can be used to see the results of the output - but it appears that the uncompressed payloads are served.  Is there a trick to get the underlying server to choose the compressed payload?

**Comment by ovhemert** [comment]
The plugin generates the compressed output when you run `gatsby build`. Running the development server with `gatsby serve` actually does not matter in this case. I've removed the last command from the documentation.

To see the result, you need to change your production webserver configuration. It needs to know when to serve the zopfli compressed .gz files.

Tricking the development server in serving the .gz files would not be right, since the pre-compressed js-files are also not production-ready. They are larger, and running the compression each time you change your code (and restart compiling your changes using live-reload) would take time and slow down development.
